apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    app: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.webserver.port }}
      nodePort: {{ .Values.webserver.nodeport }}
  type: NodePort
